server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql:///mydb?serverTimezone=GMT%2B8
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  thymeleaf:
      #关闭页面缓存
        ache: false

